### ISSUE TITLE
Plan: Update runners

### ISSUE THREAD

**Issue by timhall** [VBA-tools/Excel-TDD#7]
Tasks:
- Move runner calculations to `SpecSuite`
- Integrate inline runner into `SpecSuite` as `SpecSuite.(Print, Results, Debug, etc.)`
- Make display runner prettier: Progress, clearer failures and overall results, cleaner UI

**Comment by robodude666** [comment]
What would `SpecSuite.Debug` do?

Might be better to separate the running from the displaying, which will help in writing custom display methods without having to worry about the runner portion of it.

This will allow the runner calculations to live inside of SpecSuite, but then allow a printer/display delegate to be assigned which will get (event?) callbacks when a spec is started, "it" is ran, and final results, etc.?

The printer would only then be responsible for displaying information it's provided.

**Comment by timhall** [comment]
I agree, I think the whole idea of a "runner" doesn't work currently since the `SpecSuite` actually runs the specs.

Adding events for specs is interesting (I've been reading more about them lately, http://www.cpearson.com/excel/Events.aspx). That'll require some changes to separate `SpecSuite` creation and running (currently the runner gets the spec suite after it's run so no events would be fired). At the minimum, the goal is to move the calculations to `SpecSuite`

The main idea of `SpecSuite.(Print, Results, Debug)` was to have a simple way of output spec results to the Immediate Window, but I'll re-evaluate after I start playing with it.
